### ISSUE TITLE
[Question] How do I update an existing panel's params/props?

### ISSUE THREAD

**Issue by tjcouch-sil** [mathuo/dockview#154]
Hello! Thank you for your hard work on DockView. I have a question:

I am on Dockview version 1.5.1.

I am trying to update a panel I have added to a `DockviewReact`. In my `onReady`, I set `event.api` to a `useRef` and am also attempting to run an update on a panel like so:
```
const onReady = useCallback((event: DockviewreadyEvent) => {
    // dockviewApi is the useRef
    dockviewApi.current = event.api;

    // Add panels here, removed for brevity

    // Does not update the panel's props
    event.api.getPanel(newPanel.id)?.update({
        params: { ...dockviewApi.current.activePanel.params, ...newParams },
    });
});
```

Later, I am attempting to update the `params` of a panel (I'm using the active panel just for testing):
```
const updateScrRef = useCallback((newParams: Params) => {
    // Also does not update the panel's props
    dockviewApi.current?.activePanel?.update({
        params: { ...dockviewApi.current.activePanel.params, ...newParams },
    });
}, []);
```

For some reason, the params aka props passed into the panel don't seem to change in either case, but the panel component does indeed rerender. The props in the panel component stay the same as they were previously. It seems that the `update` function triggers a rerender on the panel component without actually passing in new params/props. Do you have any idea why this is the case?

Thank you very much for the help!

**Comment by mathuo** [comment]
Hi - I've just had a look at this and I think I've found your issue and it seems to be poor API design on my side.

To update the params of a panel in `DockviewReact` you do indeed use the `update` method however the first `params` field is suppose to be the parameters of the update method. There is a `params.params` field that is used for updating the underlying panel and I've provided a quick example below. Could you try like this and let me know if that works?

I will also take a look at simplifing this method to avoid the `params.params` notation in a new version since I agree this particular `update` method exposes a confusing API.

```tsx
setInterval(() => {
    event.api.getPanel('panel_1').update({
        params: {
            params: {
                myCustomValue: Date.now().toString(),
            },
        },
    });
}, 1000);
```

**Comment by tjcouch-sil** [comment]
Great! Thank you very much. That helps a bunch. It may be worth considering leaving the API how it is since it is already in use and just update the type files and documentation to reflect the use of this and other API methods well. It seems the type files are a bit confusing as it seems that they indicate my original post's argument to the `update` function should work if I am reading `groupPanel.d.ts` correctly:
```
export declare type GroupPanelUpdateEvent = PanelUpdateEvent<{
    params?: Parameters;
    title?: string;
}>;
```

Would you mind if I asked another couple of questions related to the API...? :) I can open another issue if you prefer.

How do I change the size of a panel? I have scoured the API to find how to do this, but nothing I run seems to work. I see some info about automatic layout sizes in the documentation, but I hope there is a way to set the size similar to dragging the borders between views.

Thank you very much for your quick response and your time taken to help with implementing this library!

**Comment by mathuo** [comment]
No problem. I will take a look at those typings as a first step. 

For the programatic resizing you can access the panels `api` object from where you can retrieve the `group` that the panel belongs too (since many panels can be within one group due to the tabbing). The group exposes it's own `api` object from where you can programatically set a width and/or height.

Noticed this feature isn't well documentation so will add something to the documentation on this too!

I've created a quick example in a sandbox to show this too [here](https://codesandbox.io/s/keen-gwen-b18oz5?file=/src/App.tsx:254-316).

```tsx
props.api.group.api.setSize({
        height: 150
});
```

```tsx
props.api.group.api.setSize({
        width: 150
});
```

**Comment by tjcouch-sil** [comment]
I may be missing something, but I don't seem to be able to set the size with the 'Go' button in your sandbox, and the following doesn't seem to work for me either:
```
ohebPanel.api.group.api.setSize({width: 40, height: 200});
```

Any thoughts for me on these things? Thank you for getting back to me on this! Really appreciate your time and intentionality.

**Comment by mathuo** [comment]
Sorry, looks like I didn't save my example correctly on the sandbox. Can you use the link [here](https://codesandbox.io/s/keen-gwen-b18oz5?file=/src/App.tsx) instead?

There is actually some inconsistancy in the current build when resizing panels in using the `DockviewReact` component but I have published an experimental build [here](https://www.npmjs.com/package/dockview/v/0.0.0-experimental-a44f4c5d-20220920) which I am using in the latest sandbox. 

The changes published in this experimental build are based on [this](https://github.com/mathuo/dockview/issues/156) branch which I will most likely get merged after adding a few more tests, this change doesn't alter the existing public APIs.

Let me know if this is the behaviour you were expecting to see the first time around?

**Comment by tjcouch-sil** [comment]
Looks great! Thank you very much for all the hard work on this! Looking forward to when this gets out to a release :) I really appreciate all the help and promptness in working through this with me. Have a wonderful day!
