### ISSUE TITLE
Website crashing

### ISSUE THREAD

**Issue by abalter** [mathuo/dockview#186]
![image](https://user-images.githubusercontent.com/5349876/220213401-56078d2f-0211-41cc-acb4-f1b2115ff108.png)

![image](https://user-images.githubusercontent.com/5349876/220213537-75615459-8e00-456b-abac-e342d366bb24.png)

**Comment by mathuo** [comment]
Sorry, this is due to some changes I've been making for an upcoming release and some mismatched versions on the docs website - this should now be fixed! Let me know if you have any problems

There are some changes in the upcoming release that are related to an issue you previously raised (https://github.com/mathuo/dockview/issues/160). Let me get the docs published for this too.
