### ISSUE TITLE
Obscuring `react-dnd` dropTargets inside of a DockView in 1.6.0

### ISSUE THREAD

**Issue by pawelngei** [mathuo/dockview#215]
I'm using [DockviewReact](https://dockview.dev/docs/components/dockview#dockviewreact-component) from `dockview@1.6.0`, inside of which there are a few other components, some of which use `react-dnd` and [`@minoru/react-dnd-treeview`](https://github.com/minop1205/react-dnd-treeview). The `DndProvider` is declared at the top of the app, way above the components mentioned.

It looks `DockviewReact` obscures all mouse (but not touch!) drop events inside of it, even with `showDndOverlay` set to false. `onDidDrop` never fires.

Meanwhile, the `react-dnd` events underneath work well with touch, but when it's mouse pointer, they emit `onDragEnd` instead of `onDrop`. Everything works well when rendered outside of the Dockview.

I did some digging and I think the offending line is https://github.com/mathuo/dockview/blob/5b1aa4221f24990a6af3489d614caec125986db1/packages/dockview-core/src/dnd/droptarget.ts#L161-L163 , but I cannot figure out if it's possible to overwrite it from outside.

Do you have any ideas?

**Comment by mathuo** [comment]
Hi - Yes I guess there could be some conflict here that I haven't accounted for in terms of external dnd events. I will certainly take a look at fixing it though since dockview shouldn't interfere with other libraries, or at a minimum it should provide a way to prevent the interferance.

Would it be possible for you to add a small example just so I can see the exact problem? Potentially adding a react-dnd item into this existing sandbox (https://codesandbox.io/s/github/mathuo/dockview/tree/master/packages/docs/sandboxes/simple-dockview) to show the problem?

**Comment by pawelngei** [comment]
Thanks for a quick response, @mathuo !

I created two example sandboxes, one with `react-dnd` on top of the tree, one inside of dockview:

https://codesandbox.io/s/dockview-treeview-4eu1p1 - top
https://codesandbox.io/s/dockview-treeview-dnd-inside-811g65 - inside

In both cases, the drag-and-drop behavior of both components is broken.

**Comment by mathuo** [comment]
Amazing, thank you. Two findings from some very quick work (so I may be wrong):

- `react-dnd` intercepts dnd events globally and will call `.preventDefault()` on `dragStart` events if it thinks the drag event isn't valid. It seems dockview doesn't set some properties which technically should be set according to some dnd specs so `react-dnd` invalids the `dragStart` events through `.preventDefault()` - you'll see this in the workings in both of your examples because the tabs and no longer be dragged. To fix this I will set some additional properties on the drag events I am creating to conform to some technicalities.

> You can see this [here](https://github.com/react-dnd/react-dnd/blob/main/packages/backend-html5/src/HTML5BackendImpl.ts#L542) in the `react-dnd` source code where it treats any drag events without a valid `dataTransfer.types` to be invalid.

- You're findings in `dropTarget.ts` seem valid to me and that calling `.stopPropagation()` here isn't great because it has the potential to interfer with external events. To fix this I will remove `.stopPropagation()` here and selectively apply it only when I know that the event should be intercepted by `dockview` and used by nobody else.

I've started a branch but will need a bit of work to fine tune the two fixes above.

**Comment by mathuo** [comment]
Closing since this is working in the latest version. Example included on docs website now with panels using third-party dnd controls at https://dockview.dev/docs/components/dockview#third-party-dnd-libraries
