### ISSUE TITLE
[BUG] dockview craches when changing from excalidraw

### ISSUE THREAD

**Issue by antoKeinanen** [mathuo/dockview#317]
## Describe the bug
When changing focus from a pane containing excalidraw the app crashes. This does not occur when changing between panes where both contain excalidraw.

## To Reproduce
https://github.com/antoKeinanen/minimal_example_excalidraw_dockview

1. Create 2 panes
    - None can contain anything
    - Other has to contain `<Excalidraw/>` from `@excalidraw/excalidraw`
2. Focus on the page containing excalidraw.
3. Change the focus to the other pane without excalidraw.
4. Dockview crashes with logs attached

## Logs
```
[vite] connecting... client.ts:18:8
[vite] connected. client.ts:150:14
Uncaught TypeError: Window.getComputedStyle: Argument 1 is not an object.
    renderScene App.tsx:1365
    componentDidUpdate App.tsx:1290
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-MYQCFY5U.js:8
    js index.js:6
    __require chunk-MYQCFY5U.js:8
    React 2
    __require chunk-MYQCFY5U.js:8
    js React
    __require chunk-MYQCFY5U.js:8
    js React
    __require chunk-MYQCFY5U.js:8
    <anonymous> react-dom_client.js:37
App.tsx:1365:6
The above error occurred in the <App> component:

App@webpack-internal:///../../components/App.tsx:186:9
InitializeApp@webpack-internal:///../../components/InitializeApp.tsx:24:82
Provider@webpack-internal:///../../../node_modules/jotai/esm/index.js:687:18
ExcalidrawBase@webpack-internal:///./index.tsx:96:464
Excalidraw
excalidraw
ReactComponentBridge@http://localhost:5173/node_modules/.vite/deps/dockview.js?v=d62f2746:6675:36
div
DockviewReact<@http://localhost:5173/node_modules/.vite/deps/dockview.js?v=d62f2746:6955:25
App@http://localhost:5173/src/App.tsx:50:71

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. localhost:5173:2367:25
Uncaught TypeError: Window.getComputedStyle: Argument 1 is not an object.
    renderScene App.tsx:1365
    componentDidUpdate App.tsx:1290
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-MYQCFY5U.js:8
    js index.js:6
    __require chunk-MYQCFY5U.js:8
    React 2
    __require chunk-MYQCFY5U.js:8
    js React
    __require chunk-MYQCFY5U.js:8
    js React
    __require chunk-MYQCFY5U.js:8
    <anonymous> react-dom_client.js:37
App.tsx:1365:6
[vite] server connection lost. polling for restart... client.ts:105:12

```

## Desktop (please complete the following information):
 - Browser: Tested on firefox, chrome, and edge.
 - Version: All latest releases (firefox: 116.0.2, chrome: 115.0.5790.171, edge: 115.0.1901.200)

## Additional context
Original repo: https://github.com/SedenionCas/Sedenion/tree/development
Development build of the repo: https://sedenion-git-development-sedenion.vercel.app/

**Comment by mathuo** [comment]
Thanks for the detailed report and demo. 

I've ran the demo app and I see the application crash and the error appears to be coming from the **excalidraw** library as shown in the below screenshots.

<img width="692" alt="Screenshot 2023-08-10 at 22 06 12" src="https://github.com/mathuo/dockview/assets/6710312/f5a47d56-3d19-48c4-a8a5-bbd28c725fd1">
<img width="374" alt="Screenshot 2023-08-10 at 22 05 56" src="https://github.com/mathuo/dockview/assets/6710312/174e730c-e6bf-4136-b149-8c280b6b7969">

Digging into this a bit further it seems the **excalidraw** error is due to the component trying to access something from the **window** that doesn't exist.

When you switch tabs in **dockview** the panel that becomes hidden is removed from the **dom** but the React component remains active (so that if you was to return to that panel the component would be as left) however this only works if some assumptions are obeyed, one of which being that component doesn't try to access the window because whilst hidden it has been removed from the window and has no access to it.

In this case the **excalidraw** React component should be destroyed when it's panel is hidden and this can be achieved with a simple wrapper that can be found on the docs website [here](https://dockview.dev/docs/components/dockview#panel-rendering).

You'll want to then wrap your panel in this `RenderWhenVisible` wrapper component.


```tsx
const components = {
  default: () => {
    return <div style={{ padding: "20px", color: "white" }}>Panel_1</div>;
  },
  excalidraw: RenderWhenVisible(() => {
    return <Excalidraw />;
  }),
};
```

If you find that you do not want to destory the component and you want it to remain active even when not visible it may be worth reading how **dockview** allows you to work with iframes too [here](https://dockview.dev/docs/components/dockview#iframes) since this would allow a particular component to remain attached to the dom even when not visible.

**Comment by antoKeinanen** [comment]
> Here is a link to a sandbox based on your example using `RenderWhenVisible`
> 
>    https://codesandbox.io/s/excalidraw-render-when-visible-forked-9zvvcn

Thank you this solution worked well. I ended up using it and caching the current canvas to `sessionStorage` on destroy.

> and another link using a similar approach where the panel is absolutely positioned and hidden as required but never removed from the dom, based on the iframe examples found on [dockview.dev](dockview.dev)
> 
>    https://codesandbox.io/s/excalidraw-absolute-position-panel-forked-csh5wv
> 

This solution would have worked better, but user input did not work for some reason (you couldn't draw any shapes).
