### ISSUE TITLE
Panels layout after popup window closed.

### ISSUE THREAD

**Issue by lionelhorn** [mathuo/dockview#483]
Using the demo provided at https://dockview.dev/#live-demo

**Is it possible to keep the panels layout after a panels has been popped out and then closed ?**
Also, is it possible to make the whole docking view "poppable" in a new window? Not just groups. But all the panels.

Start
<img width="631" alt="image" src="https://github.com/mathuo/dockview/assets/50528276/acd964f7-e7d6-4a8d-b325-56d20d398858">

After opening panel 5 in new window
<img width="859" alt="image" src="https://github.com/mathuo/dockview/assets/50528276/ec24aa5a-16f3-4bed-a951-0e50f886ab06">

After closing panel 5 from new window
<img width="628" alt="image" src="https://github.com/mathuo/dockview/assets/50528276/339d93d3-f5ee-4cde-89ca-1d9f941ed612">

**Comment by mathuo** [comment]
For the repositions of panels after closing the popout window, this one will be included with https://github.com/mathuo/dockview/issues/469

To popout the entire dockview component I'm not too sure of.

It may be possible to wrap the control in an element and 'popout' that container to a different Window using https://developer.mozilla.org/en-US/docs/Web/API/Window/open but I'm not too sure since that often requires being careful with what `window` / `document` object you are using.
