### ISSUE TITLE
compoents will be tiggered twice.

### ISSUE THREAD

**Issue by nicqchen** [mathuo/dockview#491]
**Describe the bug**
compoents will be tiggered twice.

**To Reproduce**
import { Box } from "@mui/material";
import {
  DockviewReact,
  DockviewReadyEvent,
  IDockviewPanelProps,
} from "dockview";
import "dockview/dist/styles/dockview.css";
import { useRef } from "react";
import Chart from "./Chart";

export default function WorkspaceBody() {
  const onDockviewReadyAction = (event: DockviewReadyEvent): void => {
    console.log(event);
    const panel1 = event.api.addPanel({
      id: "panel1",
      component: "Chart",
      title: "Chart",
    });
    panel1.api.setActive();
  };

  const docviewComponents = {
    Chart: (props: IDockviewPanelProps) => {
      console.log("test");
      return <div>test</div>;
    },
  };

  return (
    <>
      <Box height={"calc(100vh - 40px)"}>
        <DockviewReact
          onReady={onDockviewReadyAction}
          components={docviewComponents}
          className={"dockview-theme-dark"}
          singleTabMode="fullwidth"
          debug={true}
        ></DockviewReact>
      </Box>
    </>
  );
}

**Expected behavior**
compoents will be tiggered one.

**Screenshots**
compoents will be tiggered twice.
![image](https://github.com/mathuo/dockview/assets/14218026/ab1d3b25-f812-4385-b337-0ebee728ba59)

**Desktop (please complete the following information):**
 - Version [1.9.2]

**Additional context**

**Comment by mathuo** [comment]
I would imagine what you are describing is the React "feature" that you would see when running React version 18 onwards.

React will "double-mount" a component in development mode to force developers to fix any effects that have written that have unintentional side-effects. The component is unmounted before being mounted again and since dockview does correctly cleanup during the component unmount stage this shouldn't cause any issues for you.

What I am trying to describe can be found here in the React docs https://legacy.reactjs.org/docs/strict-mode.html#ensuring-reusable-state

I've created a quick sandbox [here](https://codesandbox.io/p/sandbox/unruffled-montalcini-4cq3lj?file=%2Fsrc%2Fapp.tsx%3A24%2C1) to demonstrate that the `onReady` function is only called once per component mounting.

Do let me know if this explains your issue?

**Comment by nicqchen** [comment]
thanks mathuo, after i removed the RestricMode from code, it worked.
