### ISSUE TITLE
Title change

### ISSUE THREAD

**Issue by JosephP91** [mathuo/dockview#5]
Hi!

I was wondering how can I change a panel title. Can you give me an example?

**Comment by mathuo** [comment]
Hi

You can change a panels title using the panel api although this seems to have broken in a previous release. This is fixed in the [following PR](https://github.com/mathuo/dockview/pull/6). A new version of dockview (0.0.21) has been published with this fix included.

Here are two examples of how to do this https://github.com/mathuo/dockview/blob/master/packages/dockview-demo/src/stories/dockview/dockview.params.stories.tsx#L83. The first uses the panel api to update the title and the second uses a parameter that the panel is passed along with a custom tab component.

**Comment by JosephP91** [comment]
I can confirm that is working! Thank you!

**Comment by amirmamaghani** [comment]
Doesn't seem to be working anymore. Example:

```
const Component = (props?: IGridviewPanelProps) => {
   
    useEffect(() => {
        const interval = setInterval(() => {

            logger.log('component_id', global.layout.getPanel(props.api.id).api.title); //works
            global.layout.getPanel(props.api.id).api.setTitle("ASDASDASD"); // not working, no error given

        }, 1000);

        return () => {
            clearInterval(interval);
        };
    }, []);

    return <ComponentChild/>;
};
```
