### ISSUE TITLE
Moving a group leaves ghost groups that can't be removed

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#596]
**Describe the bug**

There is an api to moved an existing group - `panel.api.group.api.moveTo({...});`. Doing so leaves a ghost group that contains no panels and which DOM element is not really in the DOM. Because of the last thing calling `dockviewApi.clear()` (or `.fromJSON()` that first calls `.clear()`) throws an error `Invalid grid element` on trying to remove such ghost group.

**To Reproduce**

1. Go to  https://stackblitz.com/edit/vitejs-vite-7tkeiu?file=src%2FApp.tsx&terminal=dev
2. See error in console on `event.api.clear();` call

Also you can see the 'ghost' group in console.logs there
```
initial groups
  id-1 contains panels 1 and 2
  id-2 contains panel 3
after move
  id-1 contains panels 1 and 2 (if you comment out `clear()` call)
->id-3 has no panels
  id-4 contains panel 3
```

**Expected behavior**

Moving a group should not leave any empty groups.

**Screenshots**

![image](https://github.com/mathuo/dockview/assets/1944061/e124e442-9175-4fe2-80ec-6db8faeade9d)

**Desktop (please complete the following information):**
 - Browser: Chrome on Mac
 - Version 124.0.6367.119

**Additional context**

\-

**Comment by mathuo** [comment]
Thanks for the details description!

This is now fixed in 1.13.1 - small note that the example you provided will throw an error due to the `setTimeout` and the fact that React does the "doubled-mounted" thing causing the callback to fire after the component is destroyed on the first mounting.

Removing the `setTimeout` allows everything to work ok, I will probably look at adding a method to indicate whether the api has been disposed of already which would allow the `api` to be accessed safly in a timeout callback using something like

```
if (api.isDisposed) {
    return
}
```
