### ISSUE TITLE
Nested views resize lag

### ISSUE THREAD

**Issue by vincentpalma** [mathuo/dockview#643]
When resizing the parent container, the width resizing logic of the child view lags behind.

This can be reproduced directly on [the example in the docs](https://dockview.dev/docs/advanced/nested) (I changed the background colors to make it more obvious):

![Recording 2024-07-14 at 20 48 27](https://github.com/user-attachments/assets/ac23dfb1-810e-47a2-8318-364ab8bfc6e1)

https://codesandbox.io/s/restless-firefly-rnpfyh?file=/src/app.tsx

Related: https://github.com/mathuo/dockview/issues/156#issuecomment-1252905492

**Comment by mathuo** [comment]
I have a feeling the scrollbar you see is actually the overflow scrollbar for the tabs rather than a resize lag?

**Comment by vincentpalma** [comment]
Hi,
It’s not about the scrollbar but the black area that appears on the right when you resize fast to the left.
In the docs this is almost not noticeable because it happens only on the tabs section:
![CF27433E-F8D0-410F-ACB3-57A5699C58C0](https://github.com/user-attachments/assets/a0eca7bc-7b5d-4877-ae05-9519b4cfba99)

But for some reason when we use different background colors it happens on the whole view.

**Comment by mathuo** [comment]
Ah, so dockview uses a `ResizerObserver` to determine when the components parent has resized and change it's dimensions accordingly, however this may lag a couple of frames behind the parent due to the fact it then executes the resize call within a `requestAnimationFrame` callback for performance reasons.

This frame out-of-sync'ness is seen in your example of nested dockviews.

To get around this dockview does allow the user to explicitly control the containers size. For inner dockviews you should listen to the parents resize events and then explictly resize the inner views whilst disabling the auto-resizing on the inner view with the `disableAutoResizing` props.

Working example [here](https://codesandbox.io/p/sandbox/restless-firefly-rnpfyh?file=%2Fsrc%2Fapp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyndqcbk0007356n53zu4oc1%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyndqcbk0003356n6n9az6j0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyndqcbk0004356ngyoktet0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyndqcbk0006356ndpng0yk4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.28066284320098%252C55.71933715679902%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyndqcbk0003356n6n9az6j0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyndqcbk0002356nohw03mpb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyndqcbk0003356n6n9az6j0%2522%252C%2522activeTabId%2522%253A%2522clyndqcbk0002356nohw03mpb%2522%257D%252C%2522clyndqcbk0006356ndpng0yk4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyndqcbk0005356ni34iw7w9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyndqcbk0006356ndpng0yk4%2522%252C%2522activeTabId%2522%253A%2522clyndqcbk0005356ni34iw7w9%2522%257D%252C%2522clyndqcbk0004356ngyoktet0%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyndqcbk0004356ngyoktet0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Sorry for the delayed response but I hope that clears up the question.

```tsx
const InnerDockview = (props: IDockviewPanelProps) => {
  const api = React.useRef<DockviewApi>();

  const onReady = (event: DockviewReadyEvent) => {
    api.current = event.api;
  };

  React.useEffect(() => {
    const disposable = props.api.onDidDimensionsChange((event) => {
      api.current?.layout(event.width, event.height);
    });

    return () => {
      disposable.dispose();
    };
  }, [props.api]);

  return (
    <DockviewReact
      onReady={onReady}
      components={components}
      disableAutoResizing={true}
    />
  );
};
**
```

**Comment by vincentpalma** [comment]
Thanks a lot for your detailed answer! Manual resizing indeed solves this issue.
