### ISSUE TITLE
Dragging last panel from popout group breaks layout

### ISSUE THREAD

**Issue by timadevelop** [mathuo/dockview#660]
**Describe the bug**

https://github.com/user-attachments/assets/d9b36b3b-477d-4166-9eeb-36e64adb944e

**To Reproduce**

1. Go to https://dockview.dev/demo
2. Open a panel group in a popout window
3. One-by-one bring panels back from popout group to the main window
4. Last panel will break main layout by adding empty container for some reason 

**Expected behavior**
Dragging last panel from popout group should not add empty container to the target layout.

**Screenshots**
see video above

**Desktop (please complete the following information):**
 - Browser - chrome
 - Version - latest (1.15.2)

**Additional context**
Same issue persists on my small demo with electron, so the problem is in the lib itself, not demo code.

Any ideas where to look for the cause? It's kinda hard to find the place that might operate this.

**Comment by mathuo** [comment]
When you "popout" an existing group of panels dockview maintains a "hidden" group within the primary dock so that if you are to close the popout group those panels are placed back into the same location they were originally taken from.

What you have found here is an edge case whereby the last panel is removed from the popout group into a new group in the main dock which causes issues with the popout group and it's associated hidden group not being cleaned up and managed correctly.

I've had a quick attempt at fixing this and it seems to work but will need to spend some more time to make sure I've covered all edge cases here.

**Comment by mathuo** [comment]
Fixed in 1.16.0
