### ISSUE TITLE
external dnd events for Vue component

### ISSUE THREAD

**Issue by agatta17** [mathuo/dockview#675]
There is showDndOverlay prop on DockviewReact. It would be great to implement the same prop on DockviewVue for external dnd events.

**Comment by mathuo** [comment]
`showDndOverlay` on the React component is depreciated and will be removed in a future version. It has been replaced with a method exposed on the dockview `api` object.

The same functionality is exposed through `api.onUnhandledDragOverEvent(...)` which is common to both the React and Vue versions since it's directly on the dockview `api` object provided by the `onReady` callback.

Let me know if that answers your question.

**Comment by mathuo** [comment]
Answered
