### ISSUE TITLE
Add ability to have fixed panel with no tab in DockviewReact

### ISSUE THREAD

**Issue by jpambrun** [mathuo/dockview#84]
Just been playing with this library and I have been impressed so far.

The documentation is not amazing, but I can see the upcoming branch. In the meantime, I am struggling a little bit to understand the capabilities.

I want to use DockviewReact to create a flexible layout around a principal pane that would have no header and can't be closed.

I have mocked it up below with a GridviewReact containing 2 DockviewReact.. but I would like the panel to be able to move around.
Is this possible? Otherwise, could this be considered for future enhancement? 

![image](https://user-images.githubusercontent.com/718384/165389441-ea731488-75ff-45e4-bdc0-30b0bda27bfe.png)

**Comment by mathuo** [comment]
It's not something that is currently supported although it's something intended to be supported. 

As an example I made some quick modifications, publishing them under an experimental tag on npm (https://www.npmjs.com/package/dockview/v/0.0.0-experimental-fe3d0b23-20220427?activeTab=versions) and created a quick sandbox which uses this build and I believe follows along the lines of what you are talking about:

- https://codesandbox.io/s/dockview-group-api-f4qwli?file=/src/app.tsx

This is using a ReactGridview to contain a header and a content component. The content component is using a single ReactDockview locking a particular group and hiding it's header bar. The new code can be seen here which for now is just a quick API I thought of and could change with an actual release of this feature:

```tsx
panel3.group!.model.locked = true;
panel3.group!.model.header.hidden = true;
```

Rather than manually adding each panel via the `on[Grid|Dock]viewReadyEvent` you could equally call `event.api.fromJSON(...)` in both circumstances to create these layouts from static JSON configurations. You could then listen to any changes through `event.api.onDidLayoutChange()` saving the contents of `event.api.toJSON()` to local storage and using this as the contents for `event.api.fromJSON(...)` on subsequent loads to persist layouts between sesssions.

Let me know if this covers your use case though and I can look at properly adding in this feature.

**Comment by jpambrun** [comment]
Yes! This looks and feels amazing! 

And I haven't look into the JSON bits, but it looks really powerful as well.

**Comment by jpambrun** [comment]
I tried it in the experimental build and it worked as expected. The improvements look amazing and so does the new documentation.
